import DefaultLayout from "src/layouts/DefaultLayout";

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <DefaultLayout>{children} </DefaultLayout>;
}
