import type { Metadata } from 'next';
import Link from 'next/link';
import JsonLd from '@/components/JsonLd';
import { engineeringDomains, projects, siteConfig } from '@/content/site';

export const metadata: Metadata = { title: 'Resume & Engineering Profile', description: 'Recruiter-focused engineering profile for Ariful Islam: primary strengths, representative work, current focus, location, and verified public evidence.', alternates: { canonical: '/resume' } };

export default function ResumePage() {
  return <main id="main-content" className="page-shell"><JsonLd data={{ '@context': 'https://schema.org', '@type': 'ProfilePage', name: 'Ariful Islam resume and engineering profile', url: `${siteConfig.url}/resume`, mainEntity: { '@id': `${siteConfig.url}/#person`, '@type': 'Person', name: siteConfig.name } }} /><article className="site-container">
    <header className="mx-auto max-w-5xl"><p className="section-kicker">Resume / Recruiter brief</p><h1 className="mt-5 text-balance text-4xl font-black tracking-[-0.04em] text-white sm:text-6xl">Ariful Islam — Software Engineer, Product Builder & Inventor</h1><p className="mt-6 max-w-3xl text-xl leading-9 text-slate-400">Software-led product engineering across SaaS, applied AI, backend systems, automation, and connected-product prototypes.</p><div className="mt-7 flex flex-wrap gap-3"><span className="skill-pill">{siteConfig.location}</span><span className="skill-pill">{siteConfig.timezone}</span><span className="skill-pill">{siteConfig.availability}</span></div></header>
    <div className="mx-auto mt-14 grid max-w-5xl gap-6 lg:grid-cols-[1.25fr_0.75fr]">
      <section className="surface-card p-7 sm:p-9"><h2 className="text-2xl font-black text-white">Professional profile</h2><p className="mt-5 leading-8 text-slate-400">Ariful builds maintainable software products and explores physical-digital systems. His primary delivery strength is TypeScript-based web, backend, API, data, and AI integration work. Embedded electronics, sensors, computer vision, and mechanical/CAD concepts support connected-product R&amp;D and are presented at their evidenced maturity.</p><h2 className="mt-9 text-2xl font-black text-white">Representative work</h2><div className="mt-5 space-y-4">{projects.filter((p) => p.featured).slice(0, 4).map((p) => <Link key={p.slug} href={`/work/${p.slug}`} className="link-card"><span><span className="font-semibold text-white">{p.title}</span><span className="mt-1 block text-xs text-slate-500">{p.status} · {p.year}</span></span><span>→</span></Link>)}</div></section>
      <aside className="space-y-6"><section className="surface-card p-7"><h2 className="text-xl font-bold text-white">Capability hierarchy</h2><div className="mt-5 space-y-5"><div><h3 className="text-sm font-semibold text-cyan-200">Primary expertise</h3><p className="mt-2 text-sm leading-6 text-slate-400">TypeScript, React, Next.js, Node.js, APIs, databases, product architecture, and production delivery.</p></div><div><h3 className="text-sm font-semibold text-cyan-200">Supporting capabilities</h3><p className="mt-2 text-sm leading-6 text-slate-400">Applied AI, RAG, automation, realtime systems, React Native, cloud, CI/CD, and connected-device interfaces.</p></div><div><h3 className="text-sm font-semibold text-cyan-200">Active R&amp;D and learning</h3><p className="mt-2 text-sm leading-6 text-slate-400">ESP32, Raspberry Pi, sensors, electronics and PCB research, underwater imaging, computer vision, mechanical and parametric CAD concepts.</p></div></div></section><section className="surface-card p-7"><h2 className="text-xl font-bold text-white">Public evidence</h2><div className="mt-5 flex flex-col gap-3"><a href={siteConfig.social.github} target="_blank" rel="noreferrer" className="font-semibold text-cyan-200">GitHub ↗</a><a href={siteConfig.social.linkedin} target="_blank" rel="noreferrer" className="font-semibold text-cyan-200">LinkedIn ↗</a><Link href="/work" className="font-semibold text-cyan-200">Case studies →</Link><Link href="/journal" className="font-semibold text-cyan-200">Engineering journal →</Link></div><p className="mt-5 text-xs leading-5 text-slate-500">No downloadable resume file is published in this repository. This page is the current verified recruiter brief.</p></section></aside>
    </div>
    <section className="mx-auto mt-8 max-w-5xl"><h2 className="sr-only">Full working stack</h2><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">{engineeringDomains.map((domain) => <div key={domain.title} className="surface-card p-6"><h3 className="font-bold text-white">{domain.title}</h3><p className="mt-3 text-sm leading-6 text-slate-400">{domain.skills.join(' · ')}</p></div>)}</div></section>
    <div className="mx-auto mt-10 max-w-5xl rounded-2xl border border-cyan-300/10 bg-cyan-300/[0.04] p-7 sm:flex sm:items-center sm:justify-between"><div><p className="section-kicker">Recruiting or collaborating?</p><h2 className="mt-3 text-2xl font-black text-white">Start with the role, product, and outcome.</h2></div><Link href="/#contact" className="button-primary mt-6 sm:mt-0">Contact Ariful ↗</Link></div>
  </article></main>;
}
